site_name: FaBo Humanoid Docs
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'yellow'
      accent: 'black'
    logo: 'logo.png'
    favicon: 'favicon.png'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
nav:
  - Home: "index.md"
  - Humanoid:
    - 小型: "humanoid_130.md"
    - OSS: "oss.md"
    - そのほか: "humanoid_etc.md"
  - QDD:
    - QDD: "qdd.md"
  - 強化学習:
    - RL: "rl.md"
    
extra_css:
#  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
#  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
#  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css"
  - "css/version-select.css"
  - "css/custom.css"
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
plugins:
  - macros